"""add tasks task_runs agent_runs (Phase 4)

Phase 4 的数据层：任务 / 每次执行 / Agent 节点留痕（见 docs/05-database-design.md §2、§5）。
顺带给 Phase 3 建的 tool_calls 补上 task_id / task_run_id 外键与两个索引 ——
宿主表此时才存在；这两列保持可空（Chat 侧调用没有 task_run）。

Revision ID: ddd76d59686e
Revises: 4f5ca79cbcea
Create Date: 2026-09-23 14:48:49.780881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddd76d59686e'
down_revision: Union[str, Sequence[str], None] = '4f5ca79cbcea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_org_created', 'tasks', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('run_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('failure_category', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'run_no')
    )
    op.create_index('ix_task_runs_status', 'task_runs', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('span_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    # task_id 也必须 CASCADE：否则删 task 时这条 NO ACTION 外键会挡住
    # tasks → task_runs → agent_runs 的级联链（实测报 violates foreign key constraint）
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('span_id')
    )
    op.create_index('ix_agent_runs_parent_span', 'agent_runs', ['parent_span_id'], unique=False)
    op.create_index('ix_agent_runs_task_run', 'agent_runs', ['task_run_id'], unique=False)
    op.create_index('ix_agent_runs_trace', 'agent_runs', ['trace_id'], unique=False)
    op.create_index('ix_tool_calls_parent_span', 'tool_calls', ['parent_span_id'], unique=False)
    op.create_index('ix_tool_calls_task_run', 'tool_calls', ['task_run_id'], unique=False)
    # 显式命名（autogenerate 原本给的是 None）：PostgreSQL 的 drop_constraint 必须带名字，
    # 留 None 的话 upgrade 能过、downgrade 直接报错。名字沿用 PG 的默认命名规则，
    # 与表里其它外键（tool_calls_organization_id_fkey 之类）风格一致。
    op.create_foreign_key('fk_tool_calls_task_id', 'tool_calls', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_tool_calls_task_run_id', 'tool_calls', 'task_runs', ['task_run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tool_calls_task_run_id', 'tool_calls', type_='foreignkey')
    op.drop_constraint('fk_tool_calls_task_id', 'tool_calls', type_='foreignkey')
    op.drop_index('ix_tool_calls_task_run', table_name='tool_calls')
    op.drop_index('ix_tool_calls_parent_span', table_name='tool_calls')
    op.drop_index('ix_agent_runs_trace', table_name='agent_runs')
    op.drop_index('ix_agent_runs_task_run', table_name='agent_runs')
    op.drop_index('ix_agent_runs_parent_span', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_task_runs_status', table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index('ix_tasks_org_created', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
